name: Main FILEID
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p _dist/manuals _dist/boxes
          wget https://githubdist.neruthes.xyz/optical-media-box/FILEID -O _dist/FILEID

      - name: Upload FILEID
        uses: actions/upload-artifact@v2.2.4
        with:
          path: _dist/FILEID