name: Main boxes/retro-box.jpg
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p _dist/manuals _dist/boxes
          wget https://githubdist.neruthes.xyz/optical-media-box/boxes/retro-box.jpg -O _dist/boxes/retro-box.jpg

      - name: Upload boxes/retro-box.jpg
        uses: actions/upload-artifact@v2.2.4
        with:
          path: _dist/boxes/retro-box.jpg