name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
        mkdir -p _dist/manuals _dist/boxes
        wget https://neruthesgithubdistweb.vercel.app/optical-media-box/manuals/manual-retro-cover.pdf -O _dist/manuals/manual-retro-cover.pdf
        wget https://neruthesgithubdistweb.vercel.app/optical-media-box/manuals/manual-retro.pdf -O _dist/manuals/manual-retro.pdf
        wget https://neruthesgithubdistweb.vercel.app/optical-media-box/boxes/retro-box.jpg -O _dist/boxes/retro-box.jpg


      # Upload
      - name: Upload manual-retro-cover.pdf
        uses: actions/upload-artifact@v2.2.4
        with:
          path: _dist/manuals/manual-retro-cover.pdf

      - name: Upload manual-retro.pdf
        uses: actions/upload-artifact@v2.2.4
        with:
          path: _dist/manuals/manual-retro.pdf

      - name: Upload retro-box.jpg
        uses: actions/upload-artifact@v2.2.4
        with:
          path: _dist/boxes/retro-box.jpg