name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  download-all:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p _dist/manuals _dist/boxes
          wget https://githubdist.neruthes.xyz/optical-media-box/boxes/retro-box.jpg -O _dist/boxes/retro-box.jpg
          wget https://githubdist.neruthes.xyz/optical-media-box/manuals/manual-retro-cover.pdf -O _dist/manuals/manual-retro-cover.pdf
          wget https://githubdist.neruthes.xyz/optical-media-box/manuals/manual-retro.pdf -O _dist/manuals/manual-retro.pdf

      - uses: actions/upload-artifact@v2.2.4
        with:
          path: |
            _dist/boxes/retro-box.jpg
            _dist/manuals/*.pdf
